version: '3.8'
services:
  openldap:
    image: osixia/openldap:1.5.0
    ports:
      - "389:389" # Standard LDAP port
    environment:
      LDAP_ORGANISATION: "Conduit Test"
      LDAP_DOMAIN: "conduit.rs"
      LDAP_ADMIN_PASSWORD: "admin"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

volumes:
  ldap_data:
  ldap_config:
